apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: 1006sneha/SA_backend:latest
      ports:
        - containerPort: 8085
